typography_spectrum: 0.8507532955128417
color:
  brandColors:
    - '#000000'
    - '#595a5f'
    - '#7d838f'
    - '#fdfeff'
    - '#b6b4b5'
  brandStrength: 0.4375
  lightness: 0.722269388516646
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4528255704703067
analytics:
  google: null
  facebook: null
  twitter: null
name: dueprocess
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Due Process Matters
purpose:
  - name: null
    item: null
    url: null
